version: '3.1'
services:
  rabbitmq:
    restart: always
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - default
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/CoinMarket.WebAPI/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    container_name: webapi
    ports:
      - 8080:80
    networks:
      - default
  consumer:
    image: ${DOCKER_REGISTRY-}consumer
    build:
      context: .
      dockerfile: src/CoinMarket.Consumer/Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    container_name: consumer
    networks:
        - default
networks:
  default: